# Generated by Django 6.0.3 on 2026-03-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank='True', upload_to='post', verbose_name='Thumbnail'),
        ),
    ]
